name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - pandas=1.2.3
  - pip=20.3.3
  - pytest=6.2.2
  - scipy=1.6.1
  - numpy=1.19.5
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.0